### ISSUE TITLE
Cannot build on go 1.9.3

### ISSUE THREAD

**Issue by dchw** [bitnami-labs/sealed-secrets#79]
Running a `go get github.com/bitnami-labs/sealed-secrets/cmd/kubeseal` results in the following output:

````
# github.com/bitnami/sealed-secrets/cmd/kubeseal
./main.go:179:44: cannot use codecs (type "github.com/bitnami/sealed-secrets/vendor/k8s.io/apimachinery/pkg/runtime/serializer".CodecFactory) as type "github.com/bitnami-labs/sealed-secrets/vendor/k8s.io/apimachinery/pkg/runtime/serializer".CodecFactory in argument to v1alpha1.NewSealedSecret
./main.go:179:44: cannot use secret (type *"github.com/bitnami/sealed-secrets/vendor/k8s.io/api/core/v1".Secret) as type *"github.com/bitnami-labs/sealed-secrets/vendor/k8s.io/api/core/v1".Secret in argument to v1alpha1.NewSealedSecret
./main.go:194:33: cannot use v1alpha1.SchemeGroupVersion (type "github.com/bitnami-labs/sealed-secrets/vendor/k8s.io/apimachinery/pkg/runtime/schema".GroupVersion) as type "github.com/bitnami/sealed-secrets/vendor/k8s.io/apimachinery/pkg/runtime".GroupVersioner in argument to prettyEncoder:
	"github.com/bitnami-labs/sealed-secrets/vendor/k8s.io/apimachinery/pkg/runtime/schema".GroupVersion does not implement "github.com/bitnami/sealed-secrets/vendor/k8s.io/apimachinery/pkg/runtime".GroupVersioner (wrong type for KindForGroupVersionKinds method)
		have KindForGroupVersionKinds([]"github.com/bitnami-labs/sealed-secrets/vendor/k8s.io/apimachinery/pkg/runtime/schema".GroupVersionKind) ("github.com/bitnami-labs/sealed-secrets/vendor/k8s.io/apimachinery/pkg/runtime/schema".GroupVersionKind, bool)
		want KindForGroupVersionKinds([]"github.com/bitnami/sealed-secrets/vendor/k8s.io/apimachinery/pkg/runtime/schema".GroupVersionKind) ("github.com/bitnami/sealed-secrets/vendor/k8s.io/apimachinery/pkg/runtime/schema".GroupVersionKind, bool)
./main.go:199:28: cannot use ssecret (type *v1alpha1.SealedSecret) as type "github.com/bitnami/sealed-secrets/vendor/k8s.io/apimachinery/pkg/runtime".Object in argument to "github.com/bitnami/sealed-secrets/vendor/k8s.io/apimachinery/pkg/runtime".Encode:
	*v1alpha1.SealedSecret does not implement "github.com/bitnami/sealed-secrets/vendor/k8s.io/apimachinery/pkg/runtime".Object (wrong type for DeepCopyObject method)
		have DeepCopyObject() "github.com/bitnami-labs/sealed-secrets/vendor/k8s.io/apimachinery/pkg/runtime".Object
		want DeepCopyObject() "github.com/bitnami/sealed-secrets/vendor/k8s.io/apimachinery/pkg/runtime".Object
````

I am using go 1.9.3 on macOS 10.13.2. Running a git bisect over the last few recent commits while points at commit `d086031bdd8657ff04ebc5f4f5d9ef1048da7015` as the first unbuildable commit.

Looks like some of the rename during the move changed some things?

**Comment by anguslees** [comment]
It works for me in a fresh GOPATH locally (on linux), and the travis-ci bot also built the commits successfully in its sandbox.

We moved the repo bitnami -> bitnami-labs recently, and I only very recently updated the go import paths to match.  At this point I believe it's a problem local to your environment somehow triggered by this change.  Can you try a fresh build from latest `master`?  Perhaps remove any stale built libraries from `pkg/` (or use `go build -a`)?

**Comment by dchw** [comment]
Interesting. I ran it in a fresh new `GOPATH` like this:
````
$ mkdir test-kubeseal
$ GOPATH=~/test-kubeseal go get github.com/bitnami-labs/sealed-secrets/cmd/kubeseal
````

I also cleaned my existing `GOPATH` and it worked. I am now very curious what has happened...

I'll close this for now. Sorry to bother!
